image_extension : "*.png"
frame_rate    : 25
frame_folder  : "frames"
rotated_frames_folder : "frames_rotated"
databases_folder : "databases"


# Detection
yolo_conf : 0.8
yolo_name : "Gray-320-s"


fps: 4000
cm_on_pixel_ratio: 0.0039062